/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var CLASS$=Laya.class;
var STATICATTR$=Laya.static;
var View=laya.ui.View;
var Dialog=laya.ui.Dialog;
var Scene=Laya.Scene;
if(!window.ui) window.ui={};
export {ui as default};